# Advent of Code 2021

In [1]:
from aocd.models import Puzzle
from aocd import submit
import numpy as np
import pandas as pd

## Day 1 - Sonar Sweep

In [13]:
puzzle = Puzzle(2021, 1)

In [12]:
test = np.array([199,200,208,210,200,207,240,269,290,263])
gt = np.roll(test,-1) > test
sum(gt[:-1])

7

In [18]:
data = puzzle.input_data
data = np.array([int(x) for x in data.splitlines()])

In [20]:
gt = np.roll(data, -1) > data
answer = sum(gt[:-1])

In [22]:
submit(answer, day=1, year=2021)

answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [24]:
series = pd.Series(data)
roll = series.rolling(3).sum()
answer = (roll.diff() > 0).sum()

In [ ]:
submit(answer, 'b', 1, 2021)

## Day 2 - Dive!

In [3]:
puzzle = Puzzle(2021, 2)
data = puzzle.input_data

In [10]:
class Diver:
	def __init__(self, puzzle = 'a'):
		self.h = 0
		self.v = 0
		self.aim = 0
		self.puzzle = puzzle

	def parse_line(self, line):
		direction, value = line.split(" ")
		value = int(value)
		if direction == 'forward':
			self.h += value
			if self.puzzle == 'b':
				self.v += self.aim * value
		if direction == 'backward':
			self.h -= value
		if direction == 'up':
			if self.puzzle == 'a':
				self.v -= value
			else:
				self.aim -= value
		if direction == 'down':
			if self.puzzle == 'a':
				self.v += value
			else:
				self.aim += value

In [8]:
d = Diver()
for row in data.splitlines():
	d.parse_line(row)
answer = d.h * d.v

In [9]:
submit(answer, 'a', 2, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [11]:
d = Diver('b')
for row in data.splitlines():
	d.parse_line(row)
answer = d.h * d.v

In [12]:
submit(answer, 'b', 2, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 2! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Day 3 - Binary Diagnostic

In [2]:
puzzle = Puzzle(2021, 3)
data = puzzle.input_data

In [3]:
arr = np.array([[int(x) for x in line] for line in data.splitlines()])

In [4]:
arr_df = pd.DataFrame(arr)

In [5]:
def to_decimal(x):
	return int("".join([str(int(_)) for _ in x]),2)

In [6]:
m = arr_df.mode(axis=0).astype(bool).values[0]
gamma = to_decimal(m)
epsilon = to_decimal(~m)

In [9]:
answer = gamma * epsilon

In [61]:
submit(answer, 'a',3,2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [8]:
most_common_per_bit = m.astype(int)
least_common_per_but = (~m).astype(int)


In [47]:
s = np.array([all(x) for x in (arr == most_common_per_bit)])

In [153]:
def f(array,i, most=True):
	if len(array) == 1:
		return to_decimal(array[0])
	else:
		a_df = pd.DataFrame(array)
		equals = a_df.sum(axis=0) == len(a_df)/2
		mask = a_df.mode(axis=0).astype(bool).values[0]
		mask[equals] = True
		if not most:
			mask = ~mask
		value = int(mask[i])
		l = array[:,i] == value
		array = array[l]
		return f(array, i+1, most)

In [154]:
def get_number(arr):
	return [f(arr.copy(),0, sign) for sign in [True, False]]
				

In [157]:
a = get_number(arr)

In [158]:
answer = a[0] * a[1]

In [159]:
answer

4996233

In [160]:
submit(answer, 'b',3, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 3! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Day 4 - Bingo

In [161]:
puzzle = Puzzle(2021, 4)
data = puzzle.input_data

In [165]:
l = data.splitlines()
numbers = l[0]

In [254]:
class Board:
	def __init__(self, string):
		self.arr = np.array([np.fromstring(s, sep=" ") for s in string]).astype(int)
		self.mask = np.zeros_like(self.arr).astype(bool)
		self.last_value = 0
	def add_number(self, value):
		self.mask = self.mask | (self.arr == value)
		self.last_value = value
	
	@property
	def won(self):
		row_counts = any([all(x) for x in self.mask])
		col_counts = any([all(x) for x in self.mask.T])
		return row_counts | col_counts
		
	def unmarked_sum(self):
		return self.arr[~self.mask].sum() * self.last_value

In [230]:
numbers = np.fromstring(l[0], sep=',').astype(int)

In [274]:
def make_boards():
	boards = []
	for i in range(100):
		s = 2 + (i*6)
		e = s+5
		v = l[s:e]
		b = Board(v)
		boards.append(b)
	return boards

In [256]:
boards = make_boards()
for n in numbers:
	for b in boards:
		b.add_number(n)
		if b.won:
			answer = b.unmarked_sum()
		

82440
39388
66123
80352
56916
8370
25947
28070
27268
25664
0
51590
57021
21582
1308
49704
15696
56898
49005
38115
40590
33594
6108
8340
15568
32804
35584
52820
50596
34435
30070
10670
25705
20286
20670
42930
34125
39130
33670
22344
22850
7902
7463
32047
5707
27270
30300
24240
10605
25755
23556
24915
31280
29440
10140
12168
13677
873
6890
11856
17472
4575
7560
3240
4440
11280
840
3375
4350
675
5850
4875
5400
450
854
0
0
0
0
0


In [257]:
submit(82440, 'a', 4, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [276]:
won_boards = []
boards = make_boards()
for n in numbers:
	for j,b in enumerate(boards):
		if b not in won_boards:
			b.add_number(n)
			if b.won:
				won_boards.append(b)

In [277]:
len(won_boards)

100

In [278]:
won_boards[-1].unmarked_sum()

20774

In [279]:
submit(20774,'b',4,2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 4! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Day 5 - Hydrothermal Venture

In [2]:
puzzle = Puzzle(2021,5)
data = puzzle.input_data

In [3]:
def parse_coords(x):
	coords = x.split(" ")
	x1, y1 = np.fromstring(coords[0],sep=',').astype(int)
	x2, y2 = np.fromstring(coords[-1],sep=',').astype(int)
	return np.array([x1,y1,x2,y2])

In [4]:
coords = np.array([parse_coords(x) for x in data.splitlines()])

In [69]:
class Grid:
	def __init__(self,size, include_diags=False):
		self.include_diags = include_diags
		self.grid = np.zeros(shape=(size,size))

	def add_coords(self,x1,y1,x2,y2):
		if x1 == x2:
			s,e =self.get_bounds(y1,y2)
			self.grid[x1,s:e] += 1
		elif y1 == y2:
			s,e = self.get_bounds(x1,x2)
			self.grid[s:e, y1] += 1
		elif self.include_diags:
			xd = int((x2-x1)/abs(x2-x1))
			yd = int((y2-y1)/abs(y2-y1))
			m = yd/xd
			for i in range(abs(x1-x2)+1):
				x = x1+int(i*xd)
				y = y1+int(i*yd)
				self.grid[x,y] += 1

	@staticmethod
	def get_bounds(x,y):
		if x < y:
			s = x
			e = y + 1
		else:
			s = y
			e = x + 1
		return s,e

	def __str__(self):
		s = self.grid.astype(int).astype(str)
		s[s == '0'] = '.'
		return "\n".join(["".join(list(x)) for x in s])

In [360]:
g = Grid(1000)
for c in coords:
	g.add_coords(*c)

In [331]:
answer = len(g.grid[g.grid >= 2].flatten())

In [332]:
answer

4873

In [333]:
submit(answer, 'a', 5, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [83]:
g = Grid(2500, include_diags=True)
for c in coords:
	g.add_coords(*c)
answer = len(g.grid[g.grid >= 2].flatten())

In [84]:
answer

19472

In [85]:
submit(answer,'b',5)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 5! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

In [47]:
g = Grid(10, include_diags=True)

In [78]:
t = """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""
test_coords = np.array([parse_coords(x) for x in t.splitlines()])
g = Grid(10, include_diags=True)
for c in test_coords:
	g.add_coords(*c)

In [79]:
g.grid = g.grid.T
print(g)

1.1....11.
.111...2..
..2.1.111.
...1.2.2..
.112313211
...1.2....
..1...1...
.1.....1..
1.......1.
222111....


In [82]:
g.grid[g.grid >=2].sum()

26.0

In [73]:
g = Grid(10, include_diags=True)

In [74]:
g.add_coords(1,1,3,3)


In [75]:
g.add_coords(9,7,7,9)

In [76]:
print(g)

..........
.1........
..1.......
...1......
..........
..........
..........
.........1
........1.
.......1..


In [53]:
g.grid

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

## Day 6 - Lanternfish 

In [2]:
puzzle = Puzzle(day=6, year=2021)
data = puzzle.input_data

In [3]:
class Laternfish:
	def __init__(self, days):
		self.days = days
	def count_down(self):
		if self.days == 0:
			self.days = 6
		else:
			self.days -= 1
	
	def spawn_fish(self):
		if self.days == 0:
			return Laternfish(8)
		else:
			return None

In [4]:
def count_fish(init_vals, days):
	fish_list = [Laternfish(v) for v in init_vals]
	for d in range(days):
		new_fishes = []
		for fish in fish_list:
			new_fish = fish.spawn_fish()
			fish.count_down()
			if new_fish is not None:
				new_fishes.append(new_fish)
		if len(new_fishes) > 0:
			fish_list.extend(new_fishes)
	return len(fish_list) 

In [117]:
count_fish([3,4,3,1,2], 18)

26

In [5]:
init_fish = np.fromstring(data,sep=',').astype(int)
answer = count_fish(init_fish, 80)

In [125]:
submit(answer, 'a', 6, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [182]:
def count_fish_arr(init_fish, days):
	for fish in init_fish:
		num_spawns = fish 

In [25]:
from functools import lru_cache

In [65]:
@lru_cache(1000)
def n(x,d=7):
	if x == 0:
		return 1
	if (x % d) == 0:
		return n(x-1,7) + n(x-2,8)
	else:
		return n(x-1,7)


In [142]:
def count_fish(init_fish, days):
	f = {x:0 for x in range(-1,9)}
	for v in init_fish:
		f[v] += 1
	for d in range(days):
		for k,v in f.items():
			if k >= 0:
				f[k-1] = f[k]
		f[8] = f[-1]
		f[6] += f[-1]
		f[-1] = 0
	return sum(f.values())


In [147]:
%time count_fish([3,4,3,1,2],18)

CPU times: user 31 µs, sys: 0 ns, total: 31 µs
Wall time: 33.6 µs


26

In [148]:
%time count_fish(init_fish, 18)

CPU times: user 175 µs, sys: 7 µs, total: 182 µs
Wall time: 185 µs


1570

In [149]:
%time count_fish(init_fish, 256)

CPU times: user 408 µs, sys: 0 ns, total: 408 µs
Wall time: 411 µs


1609314870967

In [150]:
answer = count_fish(init_fish, 256)

In [151]:
submit(answer, 'b', 6, 2021)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 6! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Day 7 - The Treachery of Whales

In [152]:
puzzle = Puzzle(2021,7)
data = puzzle.input_data

In [154]:
t = np.array([16,1,2,0,4,2,7,1,2,14])

In [158]:
def dist(crabs, x):
	return np.abs(crabs - x).sum()
def min_dist(crabs):
	x = set(crabs)
	return min([dist(crabs,d) for d in x])

In [161]:
crabs = np.fromstring(data, sep=',').astype(int)

In [162]:
answer = min_dist(crabs)

In [164]:
submit(answer,'a',7)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [181]:
def arr(x):
	return 0.5*(x * (x+1))
def extra_dist(crabs, x):
	return arr(np.abs(crabs - x)).sum().astype(int)
def min_dist(crabs):
	x = set(crabs)
	return min([extra_dist(crabs,d) for d in x])

In [182]:
extra_dist(t, 2).sum()

206

In [183]:
answer = min_dist(crabs)

In [184]:
submit(answer, 'b',7)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 7! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

## Days 8 - Seven Segment Search

In [5]:
from itertools import permutations

In [6]:
puzzle = Puzzle(2021, 8)
data = puzzle.input_data

In [7]:
lines = data.splitlines()

In [122]:
	{0:'abcefg',
		1:'cf',
		2:'acdeg',
		3:'acdfg',
		4:'bcdf',
		5:'abdfg',
		6:'abdefg',
		7:'acf',
		8:'abcdefg',
		9:'abcdfg'

	}.values()

dict_values(['abcefg', 'cf', 'acdeg', 'acdfg', 'bcdf', 'abdfg', 'abdefg', 'acf', 'abcdefg', 'abcdfg'])

In [221]:
letters = ['a','b','c','d','e','f','g']
values = sorted(['abcefg', 'cf', 'acdeg', 'acdfg', 'bcdf', 'abdfg', 'abdefg', 'acf', 'abcdefg', 'abcdfg'],key=len)
perms = {}

def swap_letters(perm, digits):
	d = {perm[i]:x for i,x in enumerate(letters)}
	vals = []
	for digit in digits:
		x = ''.join(sorted([d[c] for c in digit]))
		vals.append(x)
	return vals

for perm in permutations(letters, 7):
	d = {letters[i]: perm[i] for i in range(7)}
	perms[perm] = swap_letters(perm, values)
	
def try_map(m, v1, v2):
	for v in v1:	
		vn = ''.join(sorted([m[x] for x in v]))
		if vn not in v2:
			return False
	return True



class Signal:
	segment_dict = {'a':[0,2,3,5,6,7,8,9],
'b':[0,4,5,6,8,9],
'c':[0,1,2,3,4,7,8,9],
'd':[2,3,4,5,6,8,9],
'e':[0,2,6,8],
'f':[0,1,3,4,5,6,7,8,9],
'g':[0,2,3,5,6,8,9]}
	number_dict = {
		'abcefg':0,
		'cf':1,
		'acdeg':2,
		'acdfg':3,
		'bcdf':4,
		'abdfg':5,
		'abdefg':6,
		'acf':7,
		'abcdefg':8,
		'abcdfg':9

	}
	# number_lengths = {k:len(v) for k,v in Signal.number_dict.items()}
	perms = perms



	def __init__(self, string) -> None:
		self.digits, self.number = [x.split(" ") for x in string.split("|")]
		self.number = [x for x in self.number if x != '']
		self.digits = self.digits[:-1]
		self.digits = sorted(self.digits, key=len)
		self.digits = [''.join(sorted(x)) for x in self.digits]

	def count_numbers(self):
		counts = np.array([len(x) for x in self.number])
		uniques = [1,4,7,8]
		dig_count = {}
		for i in uniques:
			v = self.number_lengths[i]
			dig_count[i] = sum(counts == v)
		return dig_count

	def decode(self):
		for k, v in self.perms.items():
			if all([x in v for x in self.digits]):
				return k, v

	def get_number(self):
		code = {x:v for x,v in zip(letters, self.decode()[0])}
		vs =[]
		for digit in self.number:
			v = [code[d] for d in digit]
			v = ''.join(sorted(v))
			vs.append(str(self.number_dict[v]))
		return int(''.join(vs))
		


In [222]:
test = Signal("acedgfb cdfbe gcdfa fbcad dab cefabd cdfgeb eafb cagedb ab |cdfeb fcadb cdfeb cdbaf")

In [226]:
signals = [Signal(l) for l in lines]

In [47]:
counts = [s.count_numbers() for s in signals]

In [52]:
answer =  pd.DataFrame(counts).sum().sum()

In [54]:
submit(answer, 'a',8)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [229]:
answer = sum([s.get_number() for s in signals])

In [230]:
submit(answer, 'b',8)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 8! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>

In [228]:
sum(answer)

1084606

## Day 9 - Smoke Basin

In [232]:
puzzle = Puzzle(2021, 9)
data = puzzle.input_data

In [313]:
test = """2199943210
3987894921
9856789892
8767896789
9899965678""".splitlines()

arr1 = np.array([[int(x) for x in t] for t in test])

In [274]:
def find_low_points(arr):
	up = arr.shift(1).fillna(1e6)
	down = arr.shift(-1).fillna(1e6)
	left = arr.T.shift(1).T.fillna(1e6)
	right = arr.T.shift(-1).T.fillna(1e6)
	v = (arr < up) & (arr < down) & (arr < left) & (arr < right)
	return v

def risk_level(arr):
	lp = find_low_points(arr)
	return int((arr[lp] + 1).sum().sum())

In [275]:
risk_level(arr)

15

In [276]:
arr = np.array([[int(x) for x in t] for t in data.splitlines()])

In [278]:
arr_df = pd.DataFrame(arr)

In [279]:
answer = risk_level(arr_df)

In [281]:
submit(answer,'a',9)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

In [314]:
dx,dy = np.gradient(arr1)
dxx, dxy = np.gradient(dx)
dyx, dyy = np.gradient(dy)

In [325]:
arr

array([[5, 4, 5, ..., 1, 0, 1],
       [4, 3, 4, ..., 2, 1, 3],
       [3, 2, 3, ..., 9, 2, 4],
       ...,
       [9, 8, 7, ..., 4, 5, 6],
       [9, 7, 6, ..., 9, 6, 8],
       [7, 6, 5, ..., 8, 7, 9]])

In [311]:
ix = (dx == 0) & (dy == 0) & (dxx > 0) & (dyy > 0)

In [318]:
def basin(arr):
	bounds = arr == 9
	

array([[-1. ,  3.5,  4. ,  0. , -2.5, -3. , -1. , -1. , -1. , -1. ],
       [ 6. ,  2.5, -1. ,  0. ,  1. , -2. ,  0. , -1. , -4. , -1. ],
       [-1. , -2. , -1. ,  1. ,  1. ,  1. ,  0. ,  0. , -3. , -7. ],
       [-1. , -1. ,  0. ,  1. ,  1. , -1. , -1. ,  1. ,  1. ,  1. ],
       [-1. ,  0. ,  0.5,  0. , -1.5, -2. ,  0. ,  1. ,  1. ,  1. ]])

In [327]:
arr1 == 9

array([[False, False,  True,  True,  True, False, False, False, False,
        False],
       [False,  True, False, False, False,  True, False,  True, False,
        False],
       [ True, False, False, False, False, False,  True, False,  True,
        False],
       [False, False, False, False, False,  True, False, False, False,
         True],
       [ True, False,  True,  True,  True, False, False, False, False,
        False]])